require File.join(File.dirname(__FILE__), 'jisx0208')

ENCODES = [
  {
    :name => "ISO-2022-JP-KDDI",
    :src_zone => [0x21..0x7E, 0x21..0x7E, 8],
    :dst_ilseq => 0xFFFE,
    :map => [ [0xE468..0xE5B4, JISX0208::Char.new(0x7521)],
              [0xE5B5..0xE5DF, JISX0208::Char.new(0x7867)],
              [0xEA80..0xEAFA, JISX0208::Char.new(0x7934)],
              [0xEAFB..0xEB0D, JISX0208::Char.new(0x7854)],
              [0xEB0E..0xEB8E, JISX0208::Char.new(0x7A51)] ],
    :conv => lambda {|x| Integer(x) },
  },
  {
    :name => "SHIFT_JIS-KDDI",
    :src_zone => [0xF3..0xFC, 0x40..0xFC, 8],
    :dst_ilseq => 0xFFFE,
    :map => [ [0xE468..0xE5B4, JISX0208::Char.from_sjis(0xF640)],
              [0xE5B5..0xE5CC, JISX0208::Char.from_sjis(0xF7E5)],
              [0xE5CD..0xE5DF, JISX0208::Char.from_sjis(0xF340)],
              [0xEA80..0xEAFA, JISX0208::Char.from_sjis(0xF353)],
              [0xEAFB..0xEB0D, JISX0208::Char.from_sjis(0xF7D2)],
              [0xEB0E..0xEB8E, JISX0208::Char.from_sjis(0xF3CF)] ],
    :conv => lambda {|x| x.to_sjis },
  },
]

def zone(*args)
  bits = args.pop
  [*args.map{|range| "0x%02X-0x%02X" % [range.begin, range.end] }, bits].join(' / ')
end

def header(params)
  (<<END_HEADER_TEMPLATE % [params[:name], zone(*params[:src_zone]), params[:dst_ilseq]])
# DO NOT EDIT THIS FILE DIRECTLY

TYPE		ROWCOL
NAME		%s
SRC_ZONE	%s
OOB_MODE	ILSEQ
DST_ILSEQ	0x%04X
DST_UNIT_BITS	16
END_HEADER_TEMPLATE
end

def generate_to_ucs(params, pairs)
  pairs.sort_by! {|u, c| c }
  name = "#{params[:name]}%UCS"
  open("#{name}.src", "w") do |io|
    io.print header(params.merge(name: name.tr('%', '/')))
    io.puts
    io.puts  "BEGIN_MAP"
    io.print pairs.inject("") {|acc, uc| acc += "0x%04X = 0x%04X\n" % uc.reverse }
    io.puts  "END_MAP"
  end
end

def generate_from_ucs(params, pairs)
  pairs.sort_by! {|u, c| u }
  name = "UCS%#{params[:name]}"
  open("#{name}.src", "w") do |io|
    io.print header(params.merge(name: name.tr('%', '/')))
    io.puts
    io.puts  "BEGIN_MAP"
    io.print pairs.inject("") {|acc, uc| acc += "0x%04X = 0x%04X\n" % uc }
    io.puts  "END_MAP"
  end
end

def make_pairs(code_map)
  pairs = code_map.inject([]) {|acc, (range, ch)|
    acc += range.map{|uni| pair = [uni, yield(ch)]; ch = ch.succ; next pair }
  }
end

ENCODES.each do |params|
  pairs = make_pairs(params[:map], &params[:conv])
  generate_to_ucs(params, pairs)
  generate_from_ucs(params, pairs)
end
