#include "regint.h"

ENC_REPLICATE("UTF8-Google", "UTF-8")
ENC_ALIAS("UTF-8-Google", "UTF8-Google")

ENC_REPLICATE("UTF8-DoCoMo", "UTF-8")
ENC_REPLICATE("UTF8-KDDI", "UTF-8")
ENC_REPLICATE("UTF8-SoftBank", "UTF-8")

ENC_ALIAS("UTF-8-DoCoMo", "UTF8-DoCoMo")
ENC_ALIAS("UTF-8-KDDI", "UTF8-KDDI")
ENC_ALIAS("UTF-8-SoftBank", "UTF8-SoftBank")

ENC_REPLICATE("Shift_JIS-DoCoMo", "Windows-31J")
ENC_REPLICATE("Shift_JIS-KDDI", "Windows-31J")
ENC_REPLICATE("Shift_JIS-SoftBank", "Windows-31J")

ENC_REPLICATE("ISO-2022-JP-KDDI", "ISO-2022-JP")
ENC_REPLICATE("stateless-ISO-2022-JP-KDDI", "stateless-ISO-2022-JP")
